;; Define the test stanza for dune test

(test
 (name test_ns)
 (deps
  test_ns
  src/flake/flake.nix
  src/shell/shell.nix
  src/flake_shell/flake.nix
  src/flake_shell/shell.nix)
 (flags (:standard)))

;; Rule to compile the Rust test file into a binary

(rule
 (targets test_ns) ; the Dune target name
 (deps test_ns.rs) ; path relative to this dune file
 (action
  (run rustc --test %{deps} -o %{targets} -A warnings -l c)))
